server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848 # 修改本机的host 文件
        service: gateway-server
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # admin-service ADMIN-SERVICE  /admin-service/** -> 微服务（ADMIN-SERVICE）
      routes:
        - id: admin-service-router
          uri: lb://admin-service   # 转发到那个目的地
          predicates:
            - Path=/admin/**
        - id: test-router
          uri: http://www.aliyun.com
          predicates:
            - Path=/product
              # http://www.baidu.com/test
            # http://www.aliyun.com/product
    sentinel:
      transport:
        dashboard: sentinel-server:8858  # sentinel-dashboard 放在ecs 里面
      datasource:
#        ds1.file:
#          file: classpath:gw-flow.json
#          ruleType: gw_flow
        ds1.nacos:
          serverAddr: nacos-server:8848
          dataId: gw-flow
          ruleType: gw_flow

#        ds2.file:
#          file: classpath:api-group.json #api-group.json 接口的分组
#          ruleType: gw_api_group
        ds2.nacos:
          serverAddr: nacos-server:8848
          dataId: api-group
          ruleType: gw_api_group
